name: Build and Test GitHub actions

on:
  push:
    branches:
    - master
    - dev
    - release/*

jobs:
  build_and_test:
    name: Build and test the GitHub Action
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v1

    - name: Run the private action
      uses: ./
      with:
        webhook_uri: ${{ secrets.WEBHOOK_URI }}
        title: ''
        summary: 'GitHub Actions Message'
        text: ''
        theme_color: ''
        sections: '[{ "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png", "activityTitle": "GitHub Action invoked",  "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}", "activityText": "Commit message: [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url }})" }]'
        actions: ''
